function [] = test()
    clear all;

    filename = "c_reference.txt";
    assert(isfile(filename));

    % read random number generated by c
    [seed, c_reference] = read_c_results(filename);

    % generate random numbers in matlab
    random_generator = lib_rand.random_generator(seed);
    matlab_compare = zeros(numel(c_reference), 1);
    for i=1:1:numel(matlab_compare)
        matlab_compare(i) = random_generator.rand();
    end

    % compare against c
    assert(max(abs(c_reference - matlab_compare)) == 0);

    % check reproduction
    random_generator.set_seed(seed);
    assert(matlab_compare(1) == random_generator.rand());

    % plot numbers
    figure(1)
    clf()
    subplot(2,1,1)
    plot(matlab_compare)
    ylim([-0.25 1.25])
    yline(max(matlab_compare), 'r')
    yline(min(matlab_compare), 'r')
    grid on
    grid minor

    % plot probability density function
    subplot(2,1,2)
    [N,edges] = histcounts(matlab_compare, 100, 'Normalization', 'pdf');
    edges_center = (edges(1:end-1) + edges(2:end)) / 2;
    plot(edges_center,N)
    ylim([0 2.0])
    xlim([-0.25 1.25])
    xline(max(matlab_compare), 'r')
    xline(min(matlab_compare), 'r')
    grid on
    grid minor
end

function [seed, c_reference] = read_c_results(filename)
    fid = fopen(filename,'rt');

    % count number of file lines
    n_lines = 0;
    tline = fgetl(fid);
    while ischar(tline)
        n_lines = n_lines+1;
        tline = fgetl(fid);
    end

    frewind(fid);

    % first line contains the seed
    seed = str2double(fgetl(fid));

    assert(round(seed) == seed);

    % read numbers
    n_numbers = n_lines - 1;
    c_reference = zeros(n_numbers, 1);
    for i=1:1:n_numbers
        c_reference(i) = str2double(fgetl(fid));
    end

    % all numbers read?
    assert(~ischar(fgetl(fid)));

    fclose(fid);
end